INFO:root:Starting CTRL API server...
INFO:root:Starting ultraut API server...
INFO:root:Starting ultraut API server...
INFO:root:Starting ultraut API server...
INFO:root:Starting ultraut API server...
INFO:root:Starting ultraut API server...
INFO:root:Starting ultraut API server...
INFO:root:Starting ultraut API server...
INFO:root:Starting ultraut API server...
INFO:root:Starting ultraut API server...
INFO:root:2024-12-09 19:05:25 - ERROR: HTTPSConnectionPool(host='10.132.136.73', port=443): Max retries exceeded with url: /v1/nodes/ultraut/ultraut (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fb0880ad0>: Failed to establish a new connection: [Errno 111] Connection refused')) 1ffb0369-c49e-4e13-a261-bd75bd966010 to ultraut. Retrying...
INFO:root:Starting ultraut API server...
INFO:root:2024-12-09 19:07:07 - ERROR: HTTPSConnectionPool(host='10.132.136.73', port=443): Max retries exceeded with url: /v1/nodes/ultraut/ultraut (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate (_ssl.c:992)'))) eced7e23-beae-4d0e-8fd5-5183ae2aef1c to ultraut. Retrying...
INFO:root:Starting ultraut API server...
INFO:root:Starting ultraut API server...
INFO:root:2024-12-09 19:13:34 - ERROR: HTTPSConnectionPool(host='10.132.136.73', port=443): Max retries exceeded with url: /v1/nodes/ultraut/heartbeat (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate (_ssl.c:992)'))) f65e054a-8e4c-41f2-ab6a-1c1d7361a7a2 to ultraut. Retrying...
INFO:root:2024-12-09 19:13:34 - ERROR: HTTPSConnectionPool(host='10.132.136.73', port=443): Max retries exceeded with url: /v1/nodes/ultraut/heartbeat (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate (_ssl.c:992)'))) f5e999a6-0fd1-478c-a4ec-b1ffd0568649 to ultraut. Retrying...
INFO:root:Starting ultraut API server...
INFO:root:2024-12-09 19:15:37 - ERROR: HTTPSConnectionPool(host='10.132.136.73', port=443): Max retries exceeded with url: /v1/nodes/ultraut/heartbeat (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate (_ssl.c:992)'))) 5ef108ce-081e-49d1-b619-082db802f301 to ultraut. Retrying...
INFO:root:2024-12-09 19:15:37 - ERROR: HTTPSConnectionPool(host='10.132.136.73', port=443): Max retries exceeded with url: /v1/nodes/ultraut/heartbeat (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate (_ssl.c:992)'))) dcd1dec9-a90f-444e-bf45-87d8d28730ed to ultraut. Retrying...
INFO:root:Starting ultraut API server...
INFO:root:2024-12-09 19:16:44 - ERROR: HTTPSConnectionPool(host='10.132.136.73', port=443): Max retries exceeded with url: /v1/nodes/ultraut/heartbeat (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate (_ssl.c:992)'))) 11f121cc-1be2-43d9-a81b-042171efa996 to ultraut. Retrying...
INFO:root:2024-12-09 19:16:44 - ERROR: HTTPSConnectionPool(host='10.132.136.73', port=443): Max retries exceeded with url: /v1/nodes/ultraut/heartbeat (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate (_ssl.c:992)'))) d827c859-27ae-4636-83a2-91f08cd25151 to ultraut. Retrying...
INFO:root:Starting ultraut API server...
INFO:root:2024-12-09 19:26:47 - ERROR: HTTPSConnectionPool(host='10.132.136.73', port=443): Max retries exceeded with url: /v1/nodes/ultraut/heartbeat (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fb1010cd0>: Failed to establish a new connection: [Errno 111] Connection refused')) 2acf2033-7a19-4bb8-a674-bb1b8418256e to ultraut. Retrying...
INFO:root:2024-12-09 19:26:47 - ERROR: HTTPSConnectionPool(host='10.132.136.73', port=443): Max retries exceeded with url: /v1/nodes/ultraut/heartbeat (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fb1013bd0>: Failed to establish a new connection: [Errno 111] Connection refused')) 1b6265f1-4755-44df-99d8-ca18248b0545 to ultraut. Retrying...
INFO:root:Starting ultraut API server...
INFO:root:2024-12-09 19:32:02 - ERROR: HTTPSConnectionPool(host='10.132.136.73', port=443): Max retries exceeded with url: /v1/nodes/ultraut/heartbeat (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate (_ssl.c:992)'))) 524b0647-d62e-4b16-a6da-cbe09fe55940 to ultraut. Retrying...
INFO:root:2024-12-09 19:32:02 - ERROR: HTTPSConnectionPool(host='10.132.136.73', port=443): Max retries exceeded with url: /v1/nodes/ultraut/heartbeat (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate (_ssl.c:992)'))) e40ba4f7-a89e-4b21-8308-22ebb0956002 to ultraut. Retrying...
INFO:root:Starting ultraut API server...
INFO:root:Starting ultraut API server...
INFO:root:Starting ultraut API server...
INFO:root:Starting ultraut API server...
INFO:root:Starting ultraut API server...
INFO:root:Starting ultraut API server...
INFO:root:Starting ultraut API server...
INFO:root:Starting ultraut API server...
INFO:root:Starting ultraut API server...
INFO:root:Starting ultraut API server...
INFO:root:Starting ultraut API server...
INFO:root:Starting ultraut API server...
INFO:root:Starting ultraut API server...
INFO:root:Starting ultraut API server...
INFO:root:Starting ultraut API server...
INFO:root:Starting ultraut API server...
INFO:root:Starting ultraut API server...
INFO:root:Starting ultraut API server...
INFO:root:Starting ultraut API server...
INFO:root:Starting ultraut API server...
INFO:root:Starting ultraut API server...
INFO:root:Starting ultraut API server...
INFO:root:Starting ultraut API server...
INFO:root:Starting ultraut API server...
INFO:root:Starting ultraut API server...
INFO:root:Starting ultraut API server...
INFO:root:Starting ultraut API server...
INFO:root:Starting ultraut API server...
INFO:root:Starting ultraut API server...
INFO:root:Starting ultraut API server...
INFO:root:Starting ultraut API server...
INFO:root:Starting ultraut API server...
INFO:root:Starting ultraut API server...
INFO:root:Starting ultraut API server...
INFO:root:Starting ultraut API server...
INFO:root:Starting ultraut API server...
INFO:root:Starting ultraut API server...
INFO:root:Starting ultraut API server...
INFO:root:Starting ultraut API server...
INFO:root:Starting ultraut API server...
INFO:root:Starting ultraut API server...
INFO:root:Starting ultraut API server...
INFO:root:Starting ultraut API server...
INFO:root:2024-12-09 20:46:35 - ERROR: HTTPSConnectionPool(host='10.132.136.73', port=443): Max retries exceeded with url: /v1/nodes/ultraut/heartbeat (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fac6dfb50>: Failed to establish a new connection: [Errno 111] Connection refused')) 696c93ab-4019-4c80-884f-81e3cb7c8bff to ultraut. Retrying...
INFO:root:2024-12-09 20:46:35 - ERROR: HTTPSConnectionPool(host='10.132.136.73', port=443): Max retries exceeded with url: /v1/nodes/ultraut/heartbeat (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fabbe9a10>: Failed to establish a new connection: [Errno 111] Connection refused')) 8607f13c-4371-47d4-95e1-5c2db312b23e to ultraut. Retrying...
INFO:root:Starting ultraut API server...
INFO:root:Starting ultraut API server...
INFO:root:Starting ultraut API server...
INFO:root:Starting ultraut API server...
INFO:root:Starting ultraut API server...
INFO:root:Starting ultraut API server...
INFO:root:Starting ultraut API server...
INFO:root:Starting ultraut API server...
INFO:root:Starting ultraut API server...
INFO:root:Starting ultraut API server...
INFO:root:Starting ultraut API server...
INFO:root:Starting ultraut API server...
INFO:root:Starting ultraut API server...
INFO:root:Starting ultraut API server...
INFO:root:Starting ultraut API server...
INFO:root:Starting ultraut API server...
INFO:root:Starting ultraut API server...
INFO:root:Starting ultraut API server...
INFO:root:Starting ultraut API server...
INFO:root:Starting ultraut API server...
INFO:root:Starting ultraut API server...
INFO:root:Starting ultraut API server...
INFO:root:Starting ultraut API server...
INFO:root:Starting ultraut API server...
INFO:root:2024-12-09 21:10:05 - ERROR: HTTPSConnectionPool(host='10.132.136.73', port=443): Max retries exceeded with url: /v1/nodes/ultraut/heartbeat (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fb2b0ee10>: Failed to establish a new connection: [Errno 111] Connection refused')) e47d8425-ba83-444e-b22a-0b76da3259dd to ultraut. Retrying...
INFO:root:Starting ultraut API server...
INFO:root:Starting ultraut API server...
INFO:root:2024-12-10 15:41:24 - ERROR: HTTPSConnectionPool(host='10.132.136.73', port=443): Max retries exceeded with url: /v1/nodes/ultraut/heartbeat (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f98b22d50>: Failed to establish a new connection: [Errno 111] Connection refused')) 9d7f9e6f-1247-4078-88dc-353d3bb5c757 to ultraut. Retrying...
INFO:root:Starting ultraut API server...
INFO:root:2024-12-10 15:42:31 - ERROR: HTTPSConnectionPool(host='10.132.136.73', port=443): Max retries exceeded with url: /v1/nodes/ultraut/heartbeat (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fb4532e50>: Failed to establish a new connection: [Errno 111] Connection refused')) 08db82a5-d74d-4bc3-8ac9-f573fcd4e492 to ultraut. Retrying...
INFO:root:Starting ultraut API server...
INFO:root:2024-12-10 15:48:56 - ERROR: HTTPSConnectionPool(host='10.132.136.73', port=443): Max retries exceeded with url: /v1/nodes/ultraut/heartbeat (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f9bcdee50>: Failed to establish a new connection: [Errno 111] Connection refused')) 19df0627-55c6-4f5a-8379-15dbe831de06 to ultraut. Retrying...
INFO:root:2024-12-10 15:48:56 - ERROR: HTTPSConnectionPool(host='10.132.136.73', port=443): Max retries exceeded with url: /v1/nodes/ultraut/heartbeat (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f9bced310>: Failed to establish a new connection: [Errno 111] Connection refused')) 013b001b-8105-4c0e-a3ef-48565b27738c to ultraut. Retrying...
INFO:root:Starting ultraut API server...
INFO:root:2024-12-10 15:49:10 - ERROR: HTTPSConnectionPool(host='10.132.136.73', port=443): Max retries exceeded with url: /v1/nodes/ultraut/heartbeat (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f8fcfef10>: Failed to establish a new connection: [Errno 111] Connection refused')) 06b9545d-cf54-49f7-b6b0-5a3187386e81 to ultraut. Retrying...
INFO:root:2024-12-10 15:49:10 - ERROR: HTTPSConnectionPool(host='10.132.136.73', port=443): Max retries exceeded with url: /v1/nodes/ultraut/heartbeat (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f8fd0d3d0>: Failed to establish a new connection: [Errno 111] Connection refused')) 08128150-ed00-46db-bc1f-ce63d0275ee0 to ultraut. Retrying...
INFO:root:Starting ultraut API server...
INFO:root:Starting ultraut API server...
INFO:root:Starting ultraut API server...
INFO:root:Starting ultraut API server...
INFO:root:Starting ultraut API server...
INFO:root:Starting ultraut API server...
INFO:root:Starting ultraut API server...
INFO:root:Starting ultraut API server...
INFO:root:Starting ultraut API server...
INFO:root:Starting ultraut API server...
INFO:root:Starting ultraut API server...
INFO:root:Starting ultraut API server...
INFO:root:Starting ultraut API server...
INFO:root:2024-12-10 18:00:12 - ERROR: HTTPSConnectionPool(host='10.132.136.73', port=443): Max retries exceeded with url: /v1/nodes/ultraut/heartbeat (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f81712d50>: Failed to establish a new connection: [Errno 111] Connection refused')) 39caac95-4626-4a6b-8a12-50f5b5e3a7ae to ultraut. Retrying...
INFO:root:2024-12-10 18:00:12 - ERROR: HTTPSConnectionPool(host='10.132.136.73', port=443): Max retries exceeded with url: /v1/nodes/ultraut/heartbeat (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f8171d590>: Failed to establish a new connection: [Errno 111] Connection refused')) bbf8d9b5-0eef-40bc-a47c-69447e76fb24 to ultraut. Retrying...
INFO:root:Starting ultraut API server...
INFO:root:Starting ultraut API server...
INFO:root:2024-12-10 18:04:21 - Command 8088b0da-146b-4145-a5d3-9e7f4dcb41f3 sent to ultraut: heartbeat
INFO:root:Starting ultraut API server...
INFO:root:2024-12-10 18:09:17 - Command ae5241f8-816d-402d-b50b-e73ef8302e31 sent to ultraut: heartbeat
